version: '3.8'

services:
  web:
    build:
       context: ./
       dockerfile: prod.dockerfile
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`pydoorn.nl`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
    volumes:
      - output_volume:/code/output/

  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/services/traefik.prod.toml:/etc/traefik/traefik.toml"
